apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-emjcooqi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-emjcooqi:e6ffca647531dac9190f0e56a24b4d2f4141b87c@sha256:0b4aea30098cb75278f88689b41be479e1676bfbc0489a172474818c5d323ab3
          name: container-image
